<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="procdump64.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OSDiagTool.Core\OSDiagTool.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="OSDiagToolForm\OSDiagFormUI.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="OSDiagToolForm\PopUpForm.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>

</Project>